<script src="<?= THEME_HOST ?>incube/js/jquery-1.12.4.min.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/js/plugin/owl.carousel.min.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/js/jquery.themepunch.tools.min.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/js/jquery.themepunch.revolution.min.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/extensions/revolution.extension.slideanims.min.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/extensions/revolution.extension.layeranimation.min.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/extensions/revolution.extension.navigation.min.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/extensions/revolution.extension.parallax.min.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/js/jquery.revolution.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/js/plugin/isotope.pkgd.min.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/js/plugin/masonry.pkgd.min.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/js/appointment-index-page.js" type="text/javascript"></script>
<script src="<?= THEME_HOST ?>incube/js/custom.js" type="text/javascript"></script>