<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
	
	class Header_file {
		var $ci;
		var $identitas;
		function __construct()
		{
			$this->ci = &get_instance();
			$this->identitas = $this->ci->db->get('ms_identitas')->row();
		}
		
		function pdf($lebar)
		{
			if($this->identitas) 
			{
				$header = '
				<table class="header">
					<tr>
						<td style="width:'.$lebar.'; text-align:left;vertical-align:top;">
							<span>
								<h1 style="font-size:24px;margin:0px 0px 0px 0px;padding:0px; "><img src="'.FILES_HOST.'/img/logo_rsud.png">'.$this->identitas->nama.'</h1>
								'.$this->identitas->alamat.' <br> Telp: '.$this->identitas->tlp.'
							<br />
				';
				
				$header .= ($this->identitas->website)?'Homepage : '.$this->identitas->website:''; 
				$header .= ($this->identitas->email)?' Email: '.$this->identitas->email:''; 
				$header .= '
							</span>
						</td>
						<td style="width:7%;">
						</td>
					</tr>
				</table>
				<br />
				';
				
			}
			else
			{
				$header = '';
			}
			
			return $header;
		}
		
		function kwitansi($lebar)
		{
			if($this->identitas) 
			{
				$header = '
				<table class="header">
					<tr>
						<td style="width:'.$lebar.'; text-align:left;vertical-align:top;">
							<span>
								<h1 style="font-size:24px;margin:0px 0px 0px 0px;padding:0px; "><b style="color:red;" >AA </b>'.$this->identitas->nama.'</h1>
								'.$this->identitas->alamat.' <br> Telp: '.$this->identitas->tlp.'
							<br />
				';
				
				$header .= ($this->identitas->website)?'Homepage : '.$this->identitas->website:''; 
				$header .= ($this->identitas->email)?'Email: '.$this->identitas->email:''; 
				$header .= '
							</span>
						</td>
						<td style="width:7%;">
						</td>
					</tr>
				</table>
				<br />
				';
				
			}
			else
			{
				$header = '';
			}
			
			return $header;
		}
	}
	
	
	/* End of file pdf.php */
	/* Location: ./application/libraries/pdf.php */
	/* Please DO NOT modify this information : */
	/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-11 19:28:12 */
/* http://harviacode.com */